# Generated by Django 4.2.5 on 2023-10-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0008_patientopdvisit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugs_requested', models.TextField(verbose_name='Drugs Requested')),
                ('status', models.CharField(choices=[('Drugs Requested', 'Drugs Requested'), ('Presciption Given', 'Presciption Given')], default='Drugs Requested', max_length=20)),
                ('opd_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opd.patientopdvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.patient')),
            ],
        ),
    ]
