# Generated by Django 4.2.5 on 2023-09-29 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_patientopdvisit_status'),
        ('lab', 'populate_available_lab_tests'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('Lab Requested', 'Lab Requested'), ('Lab Completed', 'Lab Completed')], default='Lab Requested', max_length=20)),
                ('lab_tests', models.ManyToManyField(to='lab.labtestsavailable')),
                ('opd_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opd.patientopdvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
