# Generated by Django 4.2.5 on 2023-10-05 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0008_patientopdvisit_status'),
        ('lab', '0002_labtestresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestresult',
            name='opd_visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.patientopdvisit'),
        ),
    ]
