# Generated by Django 4.2.5 on 2023-09-23 19:19

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(default='', max_length=15, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_type', models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Other', 'Other')], max_length=7)),
                ('residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.CharField(blank=True, max_length=100, null=True)),
                ('next_of_kin', models.CharField(blank=True, max_length=100, null=True)),
                ('address_next_of_kin', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=100, max_length=100, null=True)),
                ('race', models.CharField(max_length=50)),
                ('religion', models.CharField(choices=[('ISLAM', 'ISLAM'), ('CHRISTIANITY', 'CHRISTIANITY'), ('OTHER', 'OTHER')], max_length=40)),
                ('clinic_id', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
