# Generated by Django 4.2.5 on 2023-09-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(choices=[('Black/African American', 'Black/African American'), ('Asian', 'Asian'), ('White', 'White'), ('Other', 'Other')], max_length=50),
        ),
    ]
