# Generated by Django 4.2.5 on 2023-09-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0003_patient_phone_number_of_next_of_kin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='index_or_staff_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_next_of_kin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
