# Generated by Django 4.2.5 on 2023-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_patient_index_or_staff_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Other', 'Other')], default='Single', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='tribe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
