# Generated by Django 4.2.5 on 2023-09-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_patient_marital_status_patient_tribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='clinic_id',
            new_name='patient_clinic_id',
        ),
    ]
