# Generated by Django 4.2.5 on 2023-09-29 14:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opd', '0008_patientopdvisit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicianDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('symptoms', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('opd_visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opd.patientopdvisit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opd.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
